### ISSUE TITLE
Linear gradient is scaled by background image size

### ISSUE THREAD

**Issue by nexxeln** [vercel/satori#163]
# Bug report

## Description / Observed Behavior
When using linear gradient in `backgroundImage`, there's an error.

```js
backgroundImage:
            'linear-gradient(#222222 1px , transparent 1px ),linear-gradient(to right, #222222 1px , transparent 1px )',
```

```
Cannot read properties of undefined (reading 'type')
```

## Expected Behavior

Linear gradient should work.

## Reproduction

[Reproduction link](https://og-playground.vercel.app/?share=nVTRbtowFP0Vy9PEJgUIJVAaAdLWVWoftpdW20tenOQmcevEkeMQaMS_79ppSgFtleoHsM-x7_E99zotjWQM1KfLmG-CgpBK7wSs2tbMCcmAp5n2yWDiup8HTgc2PNbZCRbzqhRsh2giYNujGrb6m-BpgXgEhQbVM8ygdxry6ox6rCvNk921RLAw2se0if-DK4g0lzauFHVevGX_KFYiUcgGJz0RsugpVbIu4msppEK-ybiGc_ouZyn4HdqPgeAFMDVMFYs53ubLpws7yKTcEodoxYqqZAoZi3x1TvdrSZRx0iHvnDy_zz1_hs5s5O1vt2e_D4q1mfSVO63dv4ryX_Pftd_IEmKFUbrapP25rlVW7cK1O8zYcGi-y-0qoC5xyeWMzGcB7cmEC4FMKDDTA9qnQHKmUm7qaw5izi_Cr9IoXjKdkRhj_JxejmZXo4uZmM5HVyjj3Y7mXrcYzr3ngK6XY7O7v_YY7915N0bzPuhigg51xfHcY9AEsA2ociYOB7BTbePZlA9wl-mDxJ6dHgKZDrp9eX2T0eIVt117X7LIKJQKhm-b_Lg44fo3qAgEuYlTIL9AN1I9LcfhUeb9P3WoLM2TqqjfUvvEqb9wXYd2haW-ZxYxhHVK_YSJChwKuXzkD7vSfEB0Y1cYx3hwk4cQU1-rGvb7vw).

## Additional Context

0.0.15

**Comment by nexxeln** [comment]
Hey! It doesn't thrown an error now but still doesn't seem to work.

[Reproduction link](https://og-playground.vercel.app/?share=lVb_btMwEH6Vkyc2kLolDawd1TrEgIkhwR9sEv9EQk5yTTwSOzjO0lJV4ll4NJ4EO92W31tJpNa--5zcd9_5nDXxRYBkRqC8TgN26_LtGCBTqxjn63VlAYiQhZGagUvGtv3MJaO6s2CBigZ8AcvSmK6MdxHjsuW9yTPFFqt3givk5eN9_Y-yBaMxC_mlwiQbhPgiFtJ4i4gpbDk96v8Ipch5YBB744m5G5jN5n58VhmbaelPzFMMAYzxPZPoKyZ4Gb-I84R3cE2SZtVhpqhUHWA3aVlKfTz0UBWI3QdX8ji2nXYDrLSdvOzzpzQIGA8N4KTPX2X3MqEhGlzMOFJ5GEoaMB3j8z2nvGCcLkegJOU6YqkdxvBiBG24EiBNTCN4dOGgylfslw7jQJdjuoTy96CBrNRu6K0VT5vU-hXXmurcb1_iEuekJycACZUh4-dCKZGUsONe2EPd7vmvzN2B1GNtRQvwNg91McB4MgLHdhyX__39x-VTSBgHiTRocLNSvbphicYDDOv8Jk4tcKPUx4d6mdbLwaz5dud6bdt31ho_6gWLRQlvanF2JRKEL8xHuGYqxlMrGrcjbe3EYWWe2o07NRNz_e8ue7wNPqFju-6G-W3zfEETFpckP6E6l5TxDD4LLnqi2qlYd6jDNoMOBwCOyyXGRwG2tNpWXsPCkrDDWPpzl0RKpdnMsoqiOKqeZ33XY2Ux01_e5DKeP3MuykmmB3ewAr10v5g7x5P9n_PpsUu6wiv9gi36IAN6S3V77cJKGefrqd2ie98oe13DcnlCBii_6s6WlwVXtqMdsms1G5Old0D9aGrM72dkRERqjpmMzNakJKLPeNP2tWcbvZ7rLq-nAXp5SGYLGmc4IpiIG3a9Ss03ga5vM9MYUzkfEg8DMlMyx83mHw)

If you look at the html native output you can see the `background-image` is working there but not in the satori output. Am I doing something wrong?

**Comment by shuding** [comment]
Ah that's another bug caused by `background-size`, I'll reopen this.

Temporary workaround is to multiple 1px by `div_size / background_image_size`. So vertical lines become 1200/100 = 12px and horizontal lines become 630/100 = 6.3px: [example](https://og-playground.vercel.app/?share=lVb_btMwEH4Vy9M2JmVLmrF2ROsQAyaGBH-wSfwTCbnxNfFI7OA4S0tViWfh0XgS7GRdml-sJFJr33127rvvfMkKB4IC9jAqrwvKHnxejRHK1DKG6WpVWxCKgIWR8pCPR46z72Nr21kwqqIBH2VZGpOl8c5jWLS893mm2Hz5VnAFvNw-0P8gWzASs5DfKEiyQUggYiGNt4iYgpZzRoLvoRQ5pwaxNxqbu4FZrzfjy9rYTEt_Yp5jiJAxvmMSAsUEL-MXcZ7wDq5J0qw6zhSRqgPsJi1LSQDHM1AFQHfjWh7XcdJugLW249M-f0ooZTw0gPM-f53dm4SEYHAx40DkcSgJZTrGF3tueaHxyWm6sJCShOuYpXZVpiMLtZcogaSJy0KbxSO3vdZYjga1vmU_dTCHuijTBSp_DxvIWvOG6lr3tEmwX3etrFageoiP3fOezCCUEBkyfiWUEkkJO-uFPVXvXvDS3B3IdqytaBF6k4e6JNBobCHXcV2f__n12-cTlDCOJBDa4GanenXDEo0GGG7zG-tUP0VltPrwVDWT7aIwa74-ul45zqN1ix-Z0fm8hDe1uLwVCaDPLAB0x1QMF3Y0akfaOo_Dyjx3JndqKeb637P272b4jI7tuhvmV-X5miQsLkl-BHUlCeMZ-iS46Ilqp2LdoQ7bDDocEOKwWEB8QqGlVVV5DQtLwg5jGUx9HCmVZp5tF0VxUu9nf9NjZTPTZV7nMp7uu9flJNODR1gBs_SgmLpn44Mf08mZj7vCK_2ACn2YIfJAdJPtwkoZp6uJ06K7aZe9rmG5ZkJSkF90b8vLgivb0Q7ZtZuNydYnYPsF1ZhvZtjCIjUvmwx7K1wSwZ7p_RauYseebvQWpjDLQ-zNSZyBhSER9-xumZqvAl3bZqY3MlXzPpkBxZ6SOazXfwE)
