### ISSUE TITLE
Incompatible with  JSX dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by alysonvilela** [vercel/satori#211]
This version is not compatible with dangerouslySetInnerHTML, in case the code to transform into an image has been provided by an CMS for example.

```js
export default function handler(req: NextRequest) {
  try {

    const str = `<h1 style="color: red;">an sample text</h1>`;
    return new ImageResponse(
      <div dangerouslySetInnerHTML={{ __html: str }}></div>,
      {
        width: 1200,
        height: 630,
      }
    );
  } catch (e: any) {
    console.log(`${e.message}`);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}
```

**Comment by styfle** [comment]
This is expected since `dangerouslySetInnerHTML` is not JSX, its HTML strings. Satori doesn't parse HTML strings.

See related question here: https://github.com/vercel/satori/discussions/188#discussioncomment-3864530

That being said, Satori should probably throw a helpful error message if `dangerouslySetInnerHTML` is used.

**Comment by shuding** [comment]
Yep, I think we can throw with a helpful error message (that tells you to use a parser) if that's used.
