### ISSUE TITLE
Issues with Skier emoji (⛷)

### ISSUE THREAD

**Issue by jeffreyyoung** [vercel/satori#238]
# Bug report
* The skiier (⛷) emoji is not properly parsed when using Satori library. Snowboard (🏂) emoji does work
<img width="177" alt="image" src="https://user-images.githubusercontent.com/7776643/196523241-ea9c95ed-71b2-4f1c-82eb-b4a40aa466ff.png">
* The skiier emoji seems to breaks the playground while snowboard emoji has no issues

⛷

https://og-playground.vercel.app/?share=XZLBUoMwEIZfJRPH6aXS2AK1GdqD1Rk9eLIzXrhQCJAaEgZCW8rwJD6I7-OTuAHp1J7YfP9u_uwuDQ5VxDDFXsT3vkSo1LVgy6YxMUIp40mqKRrdE3I7GvfwwCOdXrGIl7kIaqCxYMeBmviJFyzUXEnQQiWqTA5qIHgiXzXLSiMxqVkxSLuq1Dyu1wqgNP7_5W0QfiaFqmS0VkIVoN_EcXx2hap3fmIUzaYX6OOvF5eQjratL1cm8Mp9ctHZ0sdzx8c92XN2eFRHYAQRNHeQe5ZiLgTwG0LIgIbhoSwoEm46NjX5cdSZIdTZgWEe6BRFUPw2m1vOwpo6YuZaC7jdfrFcuz_cufbJxytvYrL7h07gpX0E27p226icIpuA1ern69ubQArkDl88xio3aygxbXDXKKYPMArc7xhT2xwitq0STONAlGyMWaZ2fFPn5gfRh-4E95hhPmdbFmGqi4q17S8

## Description / Observed Behavior

What kind of issues did you encounter with Satori?

## Expected Behavior

How did you expect Satori to behave here?

## Reproduction

https://og-playground.vercel.app/?share=XZLBUoMwEIZfJRPH6aXS2AK1GdqD1Rk9eLIzXrhQCJAaEgZCW8rwJD6I7-OTuAHp1J7YfP9u_uwuDQ5VxDDFXsT3vkSo1LVgy6YxMUIp40mqKRrdE3I7GvfwwCOdXrGIl7kIaqCxYMeBmviJFyzUXEnQQiWqTA5qIHgiXzXLSiMxqVkxSLuq1Dyu1wqgNP7_5W0QfiaFqmS0VkIVoN_EcXx2hap3fmIUzaYX6OOvF5eQjratL1cm8Mp9ctHZ0sdzx8c92XN2eFRHYAQRNHeQe5ZiLgTwG0LIgIbhoSwoEm46NjX5cdSZIdTZgWEe6BRFUPw2m1vOwpo6YuZaC7jdfrFcuz_cufbJxytvYrL7h07gpX0E27p226icIpuA1ern69ubQArkDl88xio3aygxbXDXKKYPMArc7xhT2xwitq0STONAlGyMWaZ2fFPn5gfRh-4E95hhPmdbFmGqi4q17S8

## Additional Context

Satori version, and any other context about the problem here.

**Comment by wong2** [comment]
The regex used https://github.com/vercel/satori/blob/main/src/language.ts#L20 gives false negative on `⛷` as an emoji.

According to this Stack Overflow answer: https://stackoverflow.com/a/64007175 there is a simpler way to test emojis. @shuding  shall we use it?

**Comment by shuding** [comment]
Maybe https://github.com/mathiasbynens/emoji-regex

**Comment by styfle** [comment]
I can reproduce with the original link

https://og-playground.vercel.app/?share=XZLBUoMwEIZfJRPH6aXS2AK1GdqD1Rk9eLIzXrhQCJAaEgZCW8rwJD6I7-OTuAHp1J7YfP9u_uwuDQ5VxDDFXsT3vkSo1LVgy6YxMUIp40mqKRrdE3I7GvfwwCOdXrGIl7kIaqCxYMeBmviJFyzUXEnQQiWqTA5qIHgiXzXLSiMxqVkxSLuq1Dyu1wqgNP7_5W0QfiaFqmS0VkIVoN_EcXx2hap3fmIUzaYX6OOvF5eQjratL1cm8Mp9ctHZ0sdzx8c92XN2eFRHYAQRNHeQe5ZiLgTwG0LIgIbhoSwoEm46NjX5cdSZIdTZgWEe6BRFUPw2m1vOwpo6YuZaC7jdfrFcuz_cufbJxytvYrL7h07gpX0E27p226icIpuA1ern69ubQArkDl88xio3aygxbXDXKKYPMArc7xhT2xwitq0STONAlGyMWaZ2fFPn5gfRh-4E95hhPmdbFmGqi4q17S8

However, I can't reproduce if I try to copy and paste from https://emojipedia.org/skier/

So that makes me think there is something wrong with the "share url" rather than satori:

![image](https://user-images.githubusercontent.com/229881/196744553-7945c78e-9b27-449d-a57f-ecc105bec3d1.png)

**Comment by with-heart** [comment]
I receive the same `Unsupported Opentype signature <htm` error in local env when using ⛷ or other complex emoji like ❤️‍🔥

**Comment by shuding** [comment]
Hey all, this issue should be fixed by #248, and thanks for reporting all the cases! :)

**Comment by with-heart** [comment]
Thank you @shuding!
