### ISSUE TITLE
React Icons (svg components) not rendering

### ISSUE THREAD

**Issue by robertgonzales** [vercel/satori#281]
# Bug report

## Description / Observed Behavior

I'm trying to use React Icons but nothing is rendering. All that library is doing is rendering `React.createElement("svg", ....)`. I would assume since Satori is powered by svg this would work. Unfortunately I'm not seeing any errors so I'm not sure where it's going wrong.

## Expected Behavior

Render React svg components.

## Reproduction

```
import { ImageResponse } from "@vercel/og"
import { NextRequest } from "next/server"
import { RiUser2Fill } from "react-icons/ri"

export const config = {
  runtime: "experimental-edge"
}

export default async function handler(req: NextRequest) {
  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          width: "100%",
          height: "100%"
        }}>
        <RiUser2Fill style={{ height: 40, width: 40, color: "black" }} />
      </div>
    ),
    {
      width: 1200,
      height: 630
    }
  )
}
```

Here's what RiUser2Fill renders in a browser:
```
<svg
  width="40"
  height="40"
  viewBox="0 0 15 15"
  fill="none"
  style="color:black"
  xmlns="http://www.w3.org/2000/svg">
  <path
    d="M0.877014 7.49988C0.877014 3.84219 3.84216 0.877045 7.49985 0.877045C11.1575 0.877045 14.1227 3.84219 14.1227 7.49988C14.1227 11.1575 11.1575 14.1227 7.49985 14.1227C3.84216 14.1227 0.877014 11.1575 0.877014 7.49988ZM7.49985 1.82704C4.36683 1.82704 1.82701 4.36686 1.82701 7.49988C1.82701 8.97196 2.38774 10.3131 3.30727 11.3213C4.19074 9.94119 5.73818 9.02499 7.50023 9.02499C9.26206 9.02499 10.8093 9.94097 11.6929 11.3208C12.6121 10.3127 13.1727 8.97172 13.1727 7.49988C13.1727 4.36686 10.6328 1.82704 7.49985 1.82704ZM10.9818 11.9787C10.2839 10.7795 8.9857 9.97499 7.50023 9.97499C6.01458 9.97499 4.71624 10.7797 4.01845 11.9791C4.97952 12.7272 6.18765 13.1727 7.49985 13.1727C8.81227 13.1727 10.0206 12.727 10.9818 11.9787ZM5.14999 6.50487C5.14999 5.207 6.20212 4.15487 7.49999 4.15487C8.79786 4.15487 9.84999 5.207 9.84999 6.50487C9.84999 7.80274 8.79786 8.85487 7.49999 8.85487C6.20212 8.85487 5.14999 7.80274 5.14999 6.50487ZM7.49999 5.10487C6.72679 5.10487 6.09999 5.73167 6.09999 6.50487C6.09999 7.27807 6.72679 7.90487 7.49999 7.90487C8.27319 7.90487 8.89999 7.27807 8.89999 6.50487C8.89999 5.73167 8.27319 5.10487 7.49999 5.10487Z"
    fill="currentColor"
    fill-rule="evenodd"
    clip-rule="evenodd"
  />
</svg>
```

**Comment by shuding** [comment]
Might be caused by `style="color:black"` and `currentColor`, because it works here:

https://og-playground.vercel.app/?share=dVVNa9tAEP0ri0rpJV3vh7QfIsmhaqE95NRAIPjiWGtbqSwZWY6Thvz3zq40a8tQMEhvnubNm_Ey-54s29IleXJdVi_zhpB9_1a7m_d3_07IxlXrTZ-TL5yxz1-uhuCxKvvNRays9rt68QbRVe1eMerfv1edW_ZV2wC3bOvDtkF2UVfr5lfvtntPuaZ3HVLPh31frd6KFoKNrz-lnxbLP-uuPTRl0dZtB_yn1WoVq0LW7-qvy4kUZ6GHsRfFWIh-fMybW_9yvX9Zn3V2M09SNk_OBzAJvVTu-K19hRgjjPAMfkitqrqGeNM2DkPDPOcwZm_0qQbnSL1u62YP1Kbvd_lsdjwe6VHStlvPBGNs5l0lwSBY3C36zfAKs4acO0aN1oynRNPUWmOKGJDUpILb8anIQKTZ-GUWAwXnlGf6FCA8pVwIHSUQYw3EmBifk-8iLtAC8tHjtPKpi8e7KEGNAE9FSqVSRiIen5wMcZAecbQ4YkOt5lYRQSWUgDxGJZccWpNMDy1IwSXoc8uAt9SmHFrOqJaGG8BMgCLoZowJibiwVCjBVORB1zDreZsyG3SVFRD3-gz8CKq44EN9X1dS7usHf1pEHP2POPbHqJLCxP4v5vN4Bx9YbxgKWm10AVgYGYxpbTNfyGTa-9PTfgIuFIXxZ77fgU-p5kqEeUG698G48UfDy1sO84JHBr4FBZuCKMqNVsBP-oi4MNQMR2bkQZf5-Q35Hp67f7zLKAcBC7oZS6EdxBkVTENUMMEFuOIZsEO14DpgqAaeYWrIWziAp2xEqI1Yw18o4AxgNnieqI8YZjVURx69Yf6F9_Ewh_I8FFTQs9IRw4ds5LXk6oTRIGJNhTah_SFfUxvyUX_E0L4AoRMPRif5iFEfMdbHfPR34f8RN1fcdMtD18FmDlt4Sn7tDmHvuRfXtGV5Ipd1tfsPORvWsd98wxvcSfFCIttFt66a-3aXk5TB9r796eq6vSIPbVeX1zP4FpLwmVwl7c7fOvskf0_CXk9yA5s_GTZ6kqcelO7psE7y1aLeu6vEbdvn6v5t5-_D_hgQ6Pi748f2yZVJ3ncH9_HxDw
