### ISSUE TITLE
New lines are buggy

### ISSUE THREAD

**Issue by TheNoob27** [vercel/satori#315]
# Bug report

## Description / Observed Behavior
All in all Satori is amazing.
But, new lines resulted in buggy unexpected behaviour - characters after the new line not being rendered (except capital letters?). `br` element doesn't work as expected either, having no effect, but I'm unsure right now if that's already been acknowledged or not.

## Expected Behavior
New lines to behave as seen in the native html tab

## Reproduction
[playground link](https://og-playground.vercel.app/?share=hVNNb6MwEP0ro6lWubCJtyFki2gO212pe1jtoZV68YWAAXeNjcCEpCj_fcdQorTqh4TE-D37vZnxuMfEpAJDjFK54xqgsQclrvvexQCFkHlhQ5h9Y-zLzBvBTqa2eIWlsqlUfCA0U2I_oS7-KWuRWGk0cYlRbaknNlYy17-tKBtHCW1FPVGPbWNldrgxBGrn_5Lexsm_vDatTm-MMjXxF1mWnVzp1J18EiEsL8-gh-daAsYG9HjkeuOCqNnlZ5Vdc1yvOI7IToruh9kTxoDBegXBicqkUoRfMMYmaGoelHGdS1exO1PtZ4MZwGBHhlVsC0jp8J_ler66ml-u1DKYX5G6fzsP_HHxNfCfOG6ihds9JrqgTMeIbuu1272pQvCZB10hrbir4oQ6wLGqBUfyf_buOd4KpQzn-uFvrVKOQ2bRghTfkD5rnE99-1Rbi46UldREfCh8GhiObko4ei8u6T2zk5ctZAP0xRBta1hs2gJKU9KUnJtOf_TQVG4GGwx7HG4Zw-9kgeOA41AcpmLb5hjauhUeitI8yvtD5R6H7YYVybgcf5VbkY7bjsf_)

**Comment by shuding** [comment]
Fixed the `\n` bug in #352, but the `<br>` one is kinda weird - I think inside flexbox, it should be the same as [`<span>hello</span><br/><span>world</span>`](https://og-playground.vercel.app/?share=hVNRb5swEP4r1lVTXljiNYSsiOZh3aTuYdpDK_XFLwQMuDO2ZUxIivLfd4YQpdXWSkicv8_-vrvzuYdM5xxiSHKxY4qQxh0kv-17HxNScVFWLiazL5R-mgUj2IncVW-wXDRGpgdEC8n3E-rj78LyzAmtkMu0bGs1sakUpfrpeN14iivH7UQ9t40TxeFOI6i8_2t6m2Z_Sqtbld9pqS3yV0VRnF3x1IN44TFZXl9AT6daIkoH9HhkauODpNmVF5XdMlivGIzITvDum94jRgkl6xWJzlQhpET8ilI6QVPzSJ3aUviK_Rmznw1mhAx2aGhSV5EcD_9aruerm_n1Si6j-Q2qh_fzKBwXn6PwhcEmWfjdY6ILzHSM8Lbeuj1qE5OQBqSrhOMPJs2wAwyM5QzQ_-TdM7jnUmrG1NNvK3MGQ2bJAhX_IX3RuBD79qG24h0qS6GQeFf4PDAM_JQwCF5d0v_Mzl5JY1K1cZVoCH6p740Hkq0li81IthWpdY2Dc-Iu05n-EIA2fjobiHsY7h_ir2gO4-jDUDbkfNuWEDvb8gB4rZ_F48H4Z-O6YYUyPvsf9Zbn47bj8S8) but that's probably not how browsers handle it. For that one I don't think we can fix easily and not sure what's the expected behavior tbh.
