### ISSUE TITLE
Node.js regression in v0.0.45 due to use of global.atob 

### ISSUE THREAD

**Issue by tvler** [vercel/satori#366]
# Bug report

## Description / Observed Behavior

Satori is throwing an error when running in a node env that doesn't have a global.atob defined, due to this code change in 0.45 https://github.com/vercel/satori/compare/0.0.44...0.0.45#diff-65b33c89a374018f503241c1bbe295244dc0f590c0984c6953497a49a27f4958R83

Is there a more portable way to write this code? Or should satori explicitly say somewhere that the execution environment should have global.atob defined?

**Comment by shuding** [comment]
As per https://github.com/vercel/satori#runtime-and-wasm, Satori requires at least Node.js 16 (which already has `atob` available). Not just because `atob`, it also needs [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) which requires Node.js 16+ too.

**Comment by tvler** [comment]
ah apologies! I assumed the atob crash I experienced was because it wasn't supported but it was another issue altogether. Sorry!
