### ISSUE TITLE
Transform is incorect when using background-clip: text

### ISSUE THREAD

**Issue by uudens** [vercel/satori#509]
# Bug report

## Description / Observed Behavior

When using `background-clip: text` together with `transform`, the transform is incorrect.   
Seems like the problem is that satori applies the transform to both elements (`<rect>` and `<clipPath>`) so it causes the transform to be applied twice.

## Expected Behavior

Transform should be correct. Setting `background-clip: text` should not influence the element's transform.

## Reproduction

[Playground link with reproduction](https://og-playground.vercel.app/?share=pVJLTwMhEP4rEy6rCcbGR2JI9eDj4FkTe_DCLrMLlgUCs3242f8utGkTo7eeYGY-vgeZkTVeIRNsrswKEm0t3o8jKJOClVsBVWtxU3FovaM3840Crme5ys1nE7Eh410GNd4Ovatgmh4-HcAvrtIAoChdan3sM3p3t5JwcXZ1GzbnFd9jMouPeR5R7VuZrvakwRqHCZL2g1Wg5QqBNEKSPcICgk-m2JhfZtVT5GvZLLvoB6dee9nlpFXRlfGii1IZdHRGHqLpNHHIFjl0EdEdn39gvTT0eCR5siYUNdzQX4V_hof0O3tBxix4wi8cTsaZD2WQmBjZ2ijSTNzNZpxpLFGYuCmFwnromGilTcgZ9v7LvG9D2Qta76rMU1bgpa9RMUFxwIkzknVGaLTWr320ik0_)

**Comment by mrmianbao** [comment]
I have a similar issue [repro link](https://og-playground.vercel.app/?share=tVZ7T-pIFP8qTW_2PhKRviiF6G54KkJRAUEMiRnaaTs6fTidAtV4P_tOi4UiqPvH3iZNe-b8Znpev3P6whu-Cfkqf2KiBRfSGMPTlxcu8ENEke9VuRlPIAYULeCMP-JMFAYYxMmyheFqxnOvr3_PPI47CRd28uQ2Z6wlbucoMA99HNHkqExN_aDKCRsRQ4vm5SUyqZNsFQXhr9w2ByLbYcg9ReAjj0LSWkCPhone873890JK_EeYKCgBXhgAwoB7-iYIHUDI2tPIC-E-ZLK2THy33EMeNADzacaHTxE7fW9jgnhgViYQvTNqDfLRSGyyfOJeEmSvIUKw4tidA_kLSCzsLxPtAoVojtlH1srX1-SZZoTlxMAouALU4ZB5OuMT6Z65FcDqw5AIRCnVp2RRu-3N-LcNbEvA4JnAcck2XRTLnNCTRO1YlkqcLErH5VJPLB2r5a2UQO4yI3YcYSeEBsDwp3gk_soQxczCYmZitmD__6ZYCGO2eY6jTZi-tjBfyZ9m5S3ku16tvTgpMlKs3xi51ro0E4eT8AfpI8nKHnMUsfwxaQDGB-v2rbKJH3nmp4X9HnEghMz01N4cyvCxTxId8hxIUF6113m2dAiAgSjTbKl4kCEbLcDI9joUuqmrBvMZkpz6IQopsuKGz9a9tMVkkEMc22R2P3Ufd69P-tdnnn6ZqP_YQDhuDoxHO81RIwv5t3Z67cAydqZdkOCf3z7sITniZITYMjkXo0NROlimH5XqVxHKhSDtwWtmM_MOYw6EaYvbUnvjy3tvDvvzWea_yP5udjousGF1V8txP5JczHiH0iCsFouhXAA4cEAhRPaxhWwXHBu-W0SuXRRUTS5KMlSLJU3Q5LKlyEJFEUXNMKGmSQo0hblUMVVZ-6e1ChCB4amoalpFKUuC8H3IeAJoROCpfdG2y-FyjGrqfE7LUTC463Yufj9JJizcTEeFuh6LUlx7uMXGExqVupfgvK3Ld9ZZvex0rito2mvUJhdQkIaKdSNQY6T5mvP0OAoGA3p34bvy8iy8jr0GuLqlY0W25KZ8tyTG07loIWchPjeXgTG2HYkadTC-ReW4tyrVLuv94eg6FmpuydXV4MxrD1VHe4zUiqq2BH3edSslMR4UVng4gSVdjdTn9o3eaOmdunmj-lpBxJUhWNYW_WZfk88bLnIvRtqqG8bTqP9Y0KdN4VmJvKXoTX9rutyP1MnTqGDWusMxqCho0GuO4aClyf5NLEluwV3pIxyZxFicXyyWsQ7AZWta7wu3wllrMmkunmuVQafnTYX-XeXKO7cby_v7710YF64AIoWOeVq76taulbPLYXvSGPdb5335Upnxv358WB1D9Jz-yRisVQHkfVJHV5spsp0N7zEDGECQFqXnF0gq7J3ozx-gQdto3RaTNpvnS54xyWUSYNuANV828yyAw535m03LZE4ySm1mZ_aevWVP_oj3g8SHkK--8Cm_-KomCEf8mk18VUkEE84jm6-mnzvioes_oFEcJH-4dJlK7ByLxavlzqH5hns94imYM4gDMZsaPsEm__ov)

Looks like that when you provided a `clip` anything satori wraps that content in a `<rect>` and sets the clip of that rect to a <clipPath> with the clip src.

The problem is that the `transform` is applied to both the `<rect>` and the `<clipPath>` resulting in the double transform

**Comment by arguiot** [comment]
Bump. This still hasn't been fixed, and I agree with @mrmianbao, the transform is applied twice.
