### ISSUE TITLE
dynamic image

### ISSUE THREAD

**Issue by mcamprodon** [vercel/satori#512]
why this works:

```
const imageUrl = new URL('./image.png', import.meta.url)
console.log(imageUrl.pathname)
```

and this not?

```
const imagePath = './image.png'
const imageUrl = new URL(imagePath, import.meta.url)
console.log(imageUrl.pathname)
```

I need to use a dynamic image in my OG component and I don't know how.
Something like this:

```
const imagePath = './image'+id+'.png'
const imageUrl = new URL(imagePath, import.meta.url)
const image = fetch(imageUrl).then((res) => res.arrayBuffer())
```

**Comment by haneenmahd** [comment]
> why this works:
> 
> ```
> const imageUrl = new URL('./image.png', import.meta.url)
> console.log(imageUrl.pathname)
> ```
> 
> and this not?
> 
> ```
> const imagePath = './image.png'
> const imageUrl = new URL(imagePath, import.meta.url)
> console.log(imageUrl.pathname)
> ```
> 
> I need to use a dynamic image in my OG component and I don't know how. Something like this:
> 
> ```
> const imagePath = './image'+id+'.png'
> const imageUrl = new URL(imagePath, import.meta.url)
> const image = fetch(imageUrl).then((res) => res.arrayBuffer())
> ```

The first code snippet works because the URL constructor correctly resolves the relative URL './image.png' relative to the provided base URL `(import.meta.url)`. The second code snippet does not work because the URL constructor expects a valid URL as its first argument, and './image.png' is not a valid URL by itself.

**Comment by shuding** [comment]
This was because that Next.js can only track which files are used during build time, **statically**. If you do `const imageUrl = new URL('./image.png', import.meta.url)`, Next.js knows that you are using `image.png` without running your code. Then it creates a serverless function that only packs files that the code needs to use.

**Comment by shuding** [comment]
I think you have to either load the dynamic image via an API (e.g. putting all of them under public/ and fetch them on the flight), or hard code them like:

```js
imageUrl[1] = new URL('./image1.png', import.meta.url)
imageUrl[2] = new URL('./image2.png', import.meta.url)
...

const image = fetch(imageUrl[id]).then((res) => res.arrayBuffer())
```
