### ISSUE TITLE
Support for PandaCss

### ISSUE THREAD

**Issue by juliomuhlbauer** [vercel/satori#541]
# Feature Request

Support PandaCss style engine in Satori.

## Description

PandaCss is a css in js that generates styles at build time.

## Additional Context

https://panda-css.com/

**Comment by shuding** [comment]
Sorry, this is not considered as possible with the current architecture. Tailwind or inlined styles are required because Satori can't handle CSS files (or `<style>` tags) as that adds a lot of complexity. With Tailwind (`tw=`) we are able to get the element's style directly without parsing the CSS tree.
