### ISSUE TITLE
Image mask causing image to be hidden behind other SVG elements

### ISSUE THREAD

**Issue by chopfitzroy** [vercel/satori#574]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with Satori?

Child `img` elements of elements that use the `maskImage` style prop are being hidden behind one of the SVG elements.

Screenshots of the problematic SVG element:

| SVG element  | SVG element removed  |
| ------------- | ------------- |
|  <img width="1440" alt="Screenshot 2023-11-16 at 8 28 17 PM" src="https://github.com/vercel/satori/assets/2978850/3bb0a6f2-c8bb-4cdc-ae10-b1766f0f11fb">  |  <img width="1440" alt="Screenshot 2023-11-16 at 8 28 25 PM" src="https://github.com/vercel/satori/assets/2978850/04422d40-81be-4277-af3b-25b0a97efb50">   |

## Expected Behavior

How did you expect Satori to behave here?

That the image would show the same way it does in the browser (or the Native tab in the Satori playground).

## Reproduction

[Link](https://og-playground.vercel.app/?share=lVRtT9swEP4rljUJkEpSJjShbEXiTWs1sUmAYB8qDSe5pC6O7dkObajy32cnTeOyspd8cu55znfP3flWOBEp4AjvH6DRKVpNeSK4Nuji7Ov92e2Ph8nl3RiN0PFw-PEVNL6afB7fbbAOPf92c3l1s3F8_6F3XEMbxxbr0BchCmscBieeUSohtbXavBAqiH6K0BTPjJE6CkMa0DgOEhHmVXZ9_mUcwpIUksGhIwaS51M8cH6xUCmonZ4vJ0ffF_Nq49lSN761l4ou44JqTQXv8llGaNgEqLqDFMooQs3OWMf36dHxzzjsSIfroMFc-tEQUmBKxdG-OyP0KaXPSJuKwWjVhHXfgqZmFrnSN3HdNwOaz2xk35ZSLRmx6e1lDJZ7G7t4BpUxsbDAjKYp8B6SQlNjRVpIASOGPkMPEkZzPjFQaAsnwA2oHpyX2tCsuhDWzG0irwh1fdoxd0pCyAjZFbL9GGT2Ht-iWo2-KRbGiGLb9pbuLXkk1oKVxpPXjtikIDlE6LFUbP_dqpnAwNnrg8dXzBuQQJxSLg5Vc_bveoD4iZrrf76x5__pXq-MtpC0yJFWyWjVT2fQzVf9Vok97vK3antg9T91Wz60I-kvjm3CeD2gW_vDo9ikuc6Esr181AlhYGvlloJfpbpGYT9GoZ2jvw3V-qX4a8mL2T2ardXkDxdJnnIlSp7e0hfbwr3EPR1fec_Y1eV2n2z3uffY0ecdbfZl9ucDuy-mHA-wkK4vGkcr3GjFkdsAuFW2_kkhLnMcZYRpGGAoxJzeVdKtfbNo_uw9mX23V0UMKY6MKqEeYENiy5gBs5tCKJbi-hc).

## Additional Context

Satori version, and any other context about the problem here.

Satori version: `"satori": "^0.10.9"`.

I tried installing both of the following branches as they include updates to masking:

- https://github.com/vercel/satori/pull/566
- https://github.com/vercel/satori/pull/572

Neither rendered the results I wanted.

I also tried a variation of the code where I removed the absolutely position child and applied the mask to the parent.

This also works in the browser / Native tab in the satori playground, but seemed to break the SVG render even more:

<details>
  <summary>Expand alternate code sample</summary>
  
```js
() => {
  //...
  return (
    <div style={{
      width: 400,
      height: 400,
      display: 'flex',
      overflow: 'hidden',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      maskImage: `url(${props.mask})`,
      maskRepeat: 'no-repeat',
      WebkitMaskImage: `url(${props.mask})`,
      WebkitMaskRepeat: 'no-repeat',
    }}>
        <img src={submission.portrait} style={{
        top: submission.x,
        left: submission.y,
        position: 'absolute',
        maxWidth: CANVAS_WIDTH,
        maxHeight: CANVAS_HEIGHT,
        transform: `scale(${zoom})`,
      }} />
      <div style={{
        width: BORDER_WIDTH,
        height: BORDER_HEIGHT,
        backgroundSize: 'cover',
        backgroundImage: `url(${props.border})`,
        backgroundRepeat: 'no-repeat'
      }}>
      </div>
    </div>
  )
}
```

</details>

**Comment by pjeweb** [comment]
I don't think it's got to to with the nesting. The default mask mode for images in satori (and maybe the only) is luminance not alpha. So if you use the mask but with a white shape instead of black it works:

https://og-playground.vercel.app/?share=lVRtT9swEP4rljUJkNqkTGhD2YrEAK2V9iZAsEmVRl4uiYtje7ZD35T_PjtpGrcr28gn557nfPfcnW-FY54ADvDhERqeodWExZwpjS7Ov9yd3_y8H1_ejtAQnQwG73ag0dX44-h2g7Xoh6_Xl1fXG8fXbzrHNbRxbLAWXXJeGOPAO3WMQnKhjNXkhVARqscATXCutVCB7xOPRJEXc__u07cfs_ytD_OwEBT6ltif5USDJ1g2wT3rHXGZgNzrvzw9_j6bLjb-DXXjWzkJqTIqiFKEszareYAGdYBFexBcahkSvTfWyV1yfPIr8ltSfx3Umwo3GkISdCkZOrRnhN4n5AkpvaAwXNVh7Tcjic4D24A6rv1yIFluIru2hChBQ5PeQUphfrCx8yeQKeUzA-QkSYB1kOCKaCPSQBJoqMkTdGBIScbGGgpl4BiYBtmB01Jpki4uuDEzk8gOoarOWuZeSQhpLtpCNh-F1NzjWmSj0TVFXGtebNue070lL4wUp6V25DWDNi7CDAL0UEp6-GpVz6Fn7dXRww7zGgSEVinjfVmf3bvuIXok-vN_39jx_3avU0ZTSFJkSMl4uOqm02vnq3quxA53_ke1HXDxkrrN75uRdNfHNmG0HtCtLeJQTNJMpVyaXj6oOKRgamVXg1ulqkJ-N0a-maN_DdX6pbjLyYnZPpqtBeUOVxg_ZpKXLLkhS9PCg9g-HVd5x9jX5WafbPe589jT5z1tdmV25yOzLyYM9zAXti8KBytca8WB3QC4Ubb-SSAqMxykIVXQw1DwKbldCLv89az-M_ek5t1eFREkONCyhKqHdRgZRg7UbAouaYKr3w

It's still off from the browser in terms of scaling/positioning, but that seems to be another problem.

The default mask mode should be fixed with this https://github.com/vercel/satori/pull/548

**Comment by chopfitzroy** [comment]
Luminance will work and thank you for linking the relevant issue 😄 

Happy to consider this closed! ❤️
