### ISSUE TITLE
Support -webkit-text-stroke

### ISSUE THREAD

**Issue by rkalis** [vercel/satori#578]
# Feature Request
Support for the [`-webkit-text-stroke`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke) CSS property.

## Description
A big current use case for og image generation using `@vercel/og` is displaying headlines in social previews (see [this Vercel guide](https://vercel.com/guides/displaying-article-headlines-in-social-previews). Since base cover images often have varying colors throughout the image, it can be hard to read the overlaid headline without a text stroke.

That is why I think it would be a very useful addition if the `-webkit-text-stroke` property would be supported in satori.

**Comment by peterfritz** [comment]
Certainly essential! While it seems that improving Satori may not be Vercel's current top priority, adding support for `-webkit-text-stroke` would significantly enhance Satori's functionality. This is particularly important for me as a feature in my work is currently stalled in the backlog due to this limitation.

@shuding, understanding that you're likely busy, would you mind sharing your insights on this issue when time permits? Your input would be highly appreciated!
